meta_product_name: "Souvenir"
meta_title: "Souvenir - Organize and remember experiences"
meta_description: "Organize and remember experiences"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: ""   # required for Twitter Cards
